/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ajedrez_chino;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author fdhg0
 */
public class accountinfo extends javax.swing.JPanel {

    private CardLayout cardLayout;
    private JPanel contenido;

    private panelprincipal mainPanel;

    public accountinfo(panelprincipal mainPanel, JPanel contenido, CardLayout cardLayout) {
        this.cardLayout = cardLayout;
        this.mainPanel = mainPanel;
        this.contenido = contenido;
        initComponents();
        actualizarInfo();

    }

    private void actualizarInfo() {
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            usernameText.setText("USERNAME: " + loggedUser.getUsername());
            partidasGanadasText.setText("PARTIDAS GANADAS: " + loggedUser.getWins());
            fechaIngresotext.setText("FECHA DE INGRESO: " + loggedUser.getCalendar());
        } else {
            usernameText.setText("USERNAME: Not available");
            partidasGanadasText.setText("PARTIDAS GANADAS: 0");
            fechaIngresotext.setText("FECHA DE INGRESO: Not available");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountinfoText = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        partidasGanadasText = new javax.swing.JLabel();
        cambiarpasswordboton = new javax.swing.JButton();
        fechaIngresotext = new javax.swing.JLabel();
        eliminarcuentaboton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(740, 550));
        setMinimumSize(new java.awt.Dimension(740, 550));

        accountinfoText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountinfoText.setForeground(new java.awt.Color(255, 255, 255));
        accountinfoText.setText("ACCOUNT INFO");

        usernameText.setBackground(new java.awt.Color(255, 255, 255));
        usernameText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setText("USERNAME:  ");

        partidasGanadasText.setBackground(new java.awt.Color(255, 255, 255));
        partidasGanadasText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        partidasGanadasText.setForeground(new java.awt.Color(255, 255, 255));
        partidasGanadasText.setText("PARTIDAS GANADAS:");

        cambiarpasswordboton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cambiarpasswordboton.setText("CAMBIAR PASSWORD");
        cambiarpasswordboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarpasswordbotonActionPerformed(evt);
            }
        });

        fechaIngresotext.setBackground(new java.awt.Color(255, 255, 255));
        fechaIngresotext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fechaIngresotext.setForeground(new java.awt.Color(255, 255, 255));
        fechaIngresotext.setText("FECHA DE INGRESO:");

        eliminarcuentaboton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminarcuentaboton.setText("ELIMINAR CUENTA");
        eliminarcuentaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcuentabotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountinfoText)
                .addGap(296, 296, 296))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(partidasGanadasText)
                            .addComponent(usernameText)
                            .addComponent(fechaIngresotext))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cambiarpasswordboton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 260, Short.MAX_VALUE)
                        .addComponent(eliminarcuentaboton)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(accountinfoText)
                .addGap(61, 61, 61)
                .addComponent(usernameText)
                .addGap(52, 52, 52)
                .addComponent(partidasGanadasText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(fechaIngresotext)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cambiarpasswordboton)
                    .addComponent(eliminarcuentaboton))
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarpasswordbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarpasswordbotonActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();

        if (loggedUser != null) {
            String newPassword = JOptionPane.showInputDialog(this, "Ingresa tu nueva contraseña (exactamente 5 caracteres):", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);

            if (newPassword != null && newPassword.length() == 5) {
                loggedUser.setPassword(newPassword);
                JOptionPane.showMessageDialog(this, "Contraseña actualizada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "La contraseña debe tener exactamente 5 caracteres.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No hay ningún usuario logueado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cambiarpasswordbotonActionPerformed

    private void eliminarcuentabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcuentabotonActionPerformed
        // TODO add your handling code here:

        Players loggedUser = Players.getCurrentLoggedUser();

        if (loggedUser != null) {
            String password = JOptionPane.showInputDialog(this, "Ingresa su contraseña", "Eliminar Cuenta", JOptionPane.QUESTION_MESSAGE);
            if (password.equals(loggedUser.getpassword())) {
                JOptionPane.showMessageDialog(this, "Se ha eliminado la cuenta exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
                loggedUser.logout();
                Players.removePlayer(loggedUser);
                Players.setCurrentLoggedUser(null);
                cardLayout.show(contenido, "defaultPanel");
                mainPanel.loginSuccess(loggedUser);

            } else {
                JOptionPane.showMessageDialog(this, "La contraseña no coincide", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_eliminarcuentabotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountinfoText;
    private javax.swing.JButton cambiarpasswordboton;
    private javax.swing.JButton eliminarcuentaboton;
    private javax.swing.JLabel fechaIngresotext;
    private javax.swing.JLabel partidasGanadasText;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}
