/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajedrez_chino;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author fdhg0
 */
public class panelprincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;
    
    

    public panelprincipal() {
        initComponents();

        cardLayout = new CardLayout();
        contenido.setLayout(cardLayout);

        defaultpane dp = new defaultpane();
        contenido.add(dp, "defaultPanel");

        login log = new login(this);
        contenido.add(log, "loginPanel");

        crearcuenta cr = new crearcuenta();
        contenido.add(cr, "crearCuentaPanel");

        infoboton.setVisible(false);
        reportesboton.setVisible(false);
        empezarpartida.setVisible(false);

        cardLayout.show(contenido, "defaultPanel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        loginboton = new javax.swing.JButton();
        infoboton = new javax.swing.JButton();
        crear_cuentaboton = new javax.swing.JButton();
        reportesboton = new javax.swing.JButton();
        empezarpartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setMaximumSize(new java.awt.Dimension(740, 550));
        contenido.setMinimumSize(new java.awt.Dimension(740, 550));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        loginboton.setText("LOGIN");
        loginboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbotonActionPerformed(evt);
            }
        });

        infoboton.setText("VER MI INFORMACION ");
        infoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infobotonActionPerformed(evt);
            }
        });

        crear_cuentaboton.setText("CREAR CUENTA");
        crear_cuentaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_cuentabotonActionPerformed(evt);
            }
        });

        reportesboton.setText("REPORTES");
        reportesboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesbotonActionPerformed(evt);
            }
        });

        empezarpartida.setText("NUEVA PARTIDA");
        empezarpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarpartidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ajedrez Chino (Xianqui)");

        displayUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displayUser.setText("USER: GUEST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayUser, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportesboton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crear_cuentaboton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginboton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(empezarpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(displayUser))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(crear_cuentaboton)
                        .addComponent(loginboton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empezarpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(infoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(reportesboton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbotonActionPerformed
        cardLayout.show(contenido, "loginPanel");
    }//GEN-LAST:event_loginbotonActionPerformed
    public void loginSuccess(Players player) {
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            displayUser.setText("USER: " + loggedUser.getUsername());
            infoboton.setVisible(true); 
            reportesboton.setVisible(true); 
            empezarpartida.setVisible(true);


        } else {
            displayUser.setText("USER: GUEST");
            infoboton.setVisible(false); 
            reportesboton.setVisible(false); 
            empezarpartida.setVisible(false);

        }
    }
    private void crear_cuentabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_cuentabotonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contenido, "crearCuentaPanel");
    }//GEN-LAST:event_crear_cuentabotonActionPerformed

    private void reportesbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesbotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportesbotonActionPerformed

    private void infobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infobotonActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            accountinfo info = new accountinfo(this,contenido, cardLayout);
            contenido.add(info, "accountInfo");
            cardLayout.show(contenido,"accountInfo");

        } else {
            JOptionPane.showMessageDialog(null, "DEBES HACER LOG IN ANTES!!");
        }


    }//GEN-LAST:event_infobotonActionPerformed

    private void empezarpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarpartidaActionPerformed
        // TODO add your handling code here:
        TableroXiangqi tablero=new TableroXiangqi();
        tablero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_empezarpartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel contenido;
    private javax.swing.JButton crear_cuentaboton;
    private javax.swing.JLabel displayUser;
    private javax.swing.JButton empezarpartida;
    private javax.swing.JButton infoboton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginboton;
    private javax.swing.JButton reportesboton;
    // End of variables declaration//GEN-END:variables
}
