/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajedrez_chino;

import static ajedrez_chino.Players.getAllPlayers;
import java.awt.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author fdhg0
 */
public class panelprincipal extends javax.swing.JFrame {

    private CardLayout cardLayout;

    public panelprincipal() {
        initComponents();
        cardLayout = new CardLayout();
        contenido.setLayout(cardLayout);

        defaultpane dp = new defaultpane();
        contenido.add(dp, "defaultPanel");

        login log = new login(this);
        contenido.add(log, "loginPanel");

        crearcuenta cr = new crearcuenta();
        contenido.add(cr, "crearCuentaPanel");
        LoggedInpanel Lp=new LoggedInpanel();
        contenido.add(Lp,"loggedinpanel");
        infoboton.setVisible(false);
        reportesboton.setVisible(false);
        empezarpartida.setVisible(false);
        logoutboton.setVisible(false);

        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            displayUser.setText("USER: " + loggedUser.getUsername());
            infoboton.setVisible(true);
            reportesboton.setVisible(true);
            empezarpartida.setVisible(true);
            Salirboton.setVisible(false);
            cardLayout.show(contenido, "loggedinpanel");

        }else{
            cardLayout.show(contenido, "defaultPanel");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        contenido = new javax.swing.JPanel();
        loginboton = new javax.swing.JButton();
        infoboton = new javax.swing.JButton();
        crear_cuentaboton = new javax.swing.JButton();
        reportesboton = new javax.swing.JButton();
        empezarpartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        displayUser = new javax.swing.JLabel();
        Salirboton = new javax.swing.JButton();
        logoutboton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setMaximumSize(new java.awt.Dimension(740, 550));
        contenido.setMinimumSize(new java.awt.Dimension(740, 550));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        loginboton.setText("LOGIN");
        loginboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbotonActionPerformed(evt);
            }
        });

        infoboton.setText("VER MI INFORMACION ");
        infoboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infobotonActionPerformed(evt);
            }
        });

        crear_cuentaboton.setText("CREAR CUENTA");
        crear_cuentaboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_cuentabotonActionPerformed(evt);
            }
        });

        reportesboton.setText("REPORTES");
        reportesboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesbotonActionPerformed(evt);
            }
        });

        empezarpartida.setText("NUEVA PARTIDA");
        empezarpartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarpartidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Ajedrez Chino (Xiangqi)");

        displayUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Salirboton.setText("SALIR");
        Salirboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirbotonActionPerformed(evt);
            }
        });

        logoutboton.setText("LOGOUT");
        logoutboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Salirboton, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(displayUser, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(infoboton, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(reportesboton, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutboton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crear_cuentaboton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginboton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(empezarpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(displayUser))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(crear_cuentaboton)
                        .addComponent(loginboton)
                        .addComponent(logoutboton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(empezarpartida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(infoboton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(reportesboton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Salirboton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbotonActionPerformed
        cardLayout.show(contenido, "loginPanel");
    }//GEN-LAST:event_loginbotonActionPerformed
    public void loginSuccess(Players player) {
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            displayUser.setText("USER: " + loggedUser.getUsername());
            infoboton.setVisible(true);
            reportesboton.setVisible(true);
            empezarpartida.setVisible(true);
            Salirboton.setVisible(false);
            logoutboton.setVisible(true);
            cardLayout.show(contenido, "loggedinpanel");


        } else {
            displayUser.setText("");
            Salirboton.setVisible(true);
            infoboton.setVisible(false);
            reportesboton.setVisible(false);
            empezarpartida.setVisible(false);
            logoutboton.setVisible(false);

        }
    }
    private void crear_cuentabotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_cuentabotonActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contenido, "crearCuentaPanel");
    }//GEN-LAST:event_crear_cuentabotonActionPerformed

    private void reportesbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesbotonActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            RANKINGORLOGS rl = new RANKINGORLOGS(this, contenido, cardLayout);
            contenido.add(rl, "reportes");
            cardLayout.show(contenido, "reportes");
        }
    }//GEN-LAST:event_reportesbotonActionPerformed

    private void infobotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infobotonActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();
        if (loggedUser != null) {
            accountinfo info = new accountinfo(this, contenido, cardLayout);
            contenido.add(info, "accountInfo");
            cardLayout.show(contenido, "accountInfo");

        } else {
            JOptionPane.showMessageDialog(null, "DEBES HACER LOG IN ANTES!!");
        }


    }//GEN-LAST:event_infobotonActionPerformed


    private void empezarpartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarpartidaActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();

        List<Players> allUsers = Players.getAllPlayers();
        List<String> userNames = new ArrayList<>();

        for (Players user : allUsers) {
            if (!user.getUsername().equals(loggedUser.getUsername())) {
                userNames.add(user.getUsername());
            }
        }

        if (userNames.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay otros usuarios disponibles para jugar.");
            return;
        }

        String selectedOpponentName = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona a tu oponente:",
                "Elegir oponente",
                JOptionPane.PLAIN_MESSAGE,
                null,
                userNames.toArray(),
                userNames.get(0)
        );

        if (selectedOpponentName != null) {
            Players selectedOpponent = Players.getPlayerByName(selectedOpponentName);

            TableroXiangqi tablero = new TableroXiangqi(loggedUser, selectedOpponent);
            tablero.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_empezarpartidaActionPerformed

    private void SalirbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirbotonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirbotonActionPerformed

    private void logoutbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbotonActionPerformed
        // TODO add your handling code here:
        Players loggedUser = Players.getCurrentLoggedUser();
        Players.setCurrentLoggedUser(null);
        loggedUser.logout();
        loginSuccess(loggedUser);
        JOptionPane.showMessageDialog(null, "Logout Exitoso");

        cardLayout.show(contenido, "defaultPanel");

    }//GEN-LAST:event_logoutbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelprincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salirboton;
    public javax.swing.JPanel contenido;
    private javax.swing.JButton crear_cuentaboton;
    private javax.swing.JLabel displayUser;
    private javax.swing.JButton empezarpartida;
    private javax.swing.JButton infoboton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginboton;
    private javax.swing.JButton logoutboton;
    private javax.swing.JButton reportesboton;
    // End of variables declaration//GEN-END:variables
}
