/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ajedrez_chino;

import javax.swing.JButton;

/**
 *
 * @author fdhg0
 */
public class tablero extends javax.swing.JFrame {

    public tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton81 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();

        jButton81.setText("jButton81");

        jButton91.setText("jButton91");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setLayout(new java.awt.GridLayout(9, 10));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);

        jButton3.setText("jButton3");
        jPanel1.add(jButton3);

        jButton4.setText("jButton4");
        jPanel1.add(jButton4);

        jButton5.setText("jButton5");
        jPanel1.add(jButton5);

        jButton6.setText("jButton6");
        jPanel1.add(jButton6);

        jButton7.setText("jButton7");
        jPanel1.add(jButton7);

        jButton8.setText("jButton8");
        jPanel1.add(jButton8);

        jButton9.setText("jButton9");
        jPanel1.add(jButton9);

        jButton10.setText("jButton10");
        jPanel1.add(jButton10);

        jButton11.setText("jButton11");
        jPanel1.add(jButton11);

        jButton12.setText("jButton12");
        jPanel1.add(jButton12);

        jButton13.setText("jButton13");
        jPanel1.add(jButton13);

        jButton14.setText("jButton14");
        jPanel1.add(jButton14);

        jButton15.setText("jButton15");
        jPanel1.add(jButton15);

        jButton16.setText("jButton16");
        jPanel1.add(jButton16);

        jButton17.setText("jButton17");
        jPanel1.add(jButton17);

        jButton18.setText("jButton18");
        jPanel1.add(jButton18);

        jButton19.setText("jButton19");
        jPanel1.add(jButton19);

        jButton20.setText("jButton20");
        jPanel1.add(jButton20);

        jButton21.setText("jButton21");
        jPanel1.add(jButton21);

        jButton22.setText("jButton22");
        jPanel1.add(jButton22);

        jButton23.setText("jButton23");
        jPanel1.add(jButton23);

        jButton24.setText("jButton24");
        jPanel1.add(jButton24);

        jButton25.setText("jButton25");
        jPanel1.add(jButton25);

        jButton26.setText("jButton26");
        jPanel1.add(jButton26);

        jButton27.setText("jButton27");
        jPanel1.add(jButton27);

        jButton28.setText("jButton28");
        jPanel1.add(jButton28);

        jButton29.setText("jButton29");
        jPanel1.add(jButton29);

        jButton30.setText("jButton30");
        jPanel1.add(jButton30);

        jButton31.setText("jButton31");
        jPanel1.add(jButton31);

        jButton32.setText("jButton32");
        jPanel1.add(jButton32);

        jButton33.setText("jButton33");
        jPanel1.add(jButton33);

        jButton34.setText("jButton34");
        jPanel1.add(jButton34);

        jButton35.setText("jButton35");
        jPanel1.add(jButton35);

        jButton36.setText("jButton36");
        jPanel1.add(jButton36);

        jButton37.setText("jButton37");
        jPanel1.add(jButton37);

        jButton38.setText("jButton38");
        jPanel1.add(jButton38);

        jButton39.setText("jButton39");
        jPanel1.add(jButton39);

        jButton40.setText("jButton40");
        jPanel1.add(jButton40);

        jButton41.setText("jButton41");
        jPanel1.add(jButton41);

        jButton42.setText("jButton42");
        jPanel1.add(jButton42);

        jButton43.setText("jButton43");
        jPanel1.add(jButton43);

        jButton44.setText("jButton44");
        jPanel1.add(jButton44);

        jButton45.setText("jButton45");
        jPanel1.add(jButton45);

        jButton46.setText("jButton46");
        jPanel1.add(jButton46);

        jButton47.setText("jButton47");
        jPanel1.add(jButton47);

        jButton48.setText("jButton48");
        jPanel1.add(jButton48);

        jButton49.setText("jButton49");
        jPanel1.add(jButton49);

        jButton50.setText("jButton50");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton50);

        jButton51.setText("jButton51");
        jPanel1.add(jButton51);

        jButton52.setText("jButton52");
        jPanel1.add(jButton52);

        jButton53.setText("jButton53");
        jPanel1.add(jButton53);

        jButton54.setText("jButton54");
        jPanel1.add(jButton54);

        jButton55.setText("jButton55");
        jPanel1.add(jButton55);

        jButton56.setText("jButton56");
        jPanel1.add(jButton56);

        jButton57.setText("jButton57");
        jPanel1.add(jButton57);

        jButton58.setText("jButton58");
        jPanel1.add(jButton58);

        jButton59.setText("jButton59");
        jPanel1.add(jButton59);

        jButton60.setText("jButton60");
        jPanel1.add(jButton60);

        jButton61.setText("jButton61");
        jPanel1.add(jButton61);

        jButton62.setText("jButton62");
        jPanel1.add(jButton62);

        jButton63.setText("jButton63");
        jPanel1.add(jButton63);

        jButton64.setText("jButton64");
        jPanel1.add(jButton64);

        jButton65.setText("jButton65");
        jPanel1.add(jButton65);

        jButton66.setText("jButton66");
        jPanel1.add(jButton66);

        jButton67.setText("jButton67");
        jPanel1.add(jButton67);

        jButton68.setText("jButton68");
        jPanel1.add(jButton68);

        jButton69.setText("jButton69");
        jPanel1.add(jButton69);

        jButton70.setText("jButton70");
        jPanel1.add(jButton70);

        jButton71.setText("jButton71");
        jPanel1.add(jButton71);

        jButton72.setText("jButton72");
        jPanel1.add(jButton72);

        jButton73.setText("jButton73");
        jPanel1.add(jButton73);

        jButton74.setText("jButton74");
        jPanel1.add(jButton74);

        jButton75.setText("jButton75");
        jPanel1.add(jButton75);

        jButton76.setText("jButton76");
        jPanel1.add(jButton76);

        jButton77.setText("jButton77");
        jPanel1.add(jButton77);

        jButton78.setText("jButton78");
        jPanel1.add(jButton78);

        jButton79.setText("jButton79");
        jPanel1.add(jButton79);

        jButton80.setText("jButton80");
        jPanel1.add(jButton80);

        jButton82.setText("jButton82");
        jPanel1.add(jButton82);

        jButton83.setText("jButton83");
        jPanel1.add(jButton83);

        jButton84.setText("jButton84");
        jPanel1.add(jButton84);

        jButton85.setText("jButton85");
        jPanel1.add(jButton85);

        jButton86.setText("jButton86");
        jPanel1.add(jButton86);

        jButton87.setText("jButton87");
        jPanel1.add(jButton87);

        jButton88.setText("jButton88");
        jPanel1.add(jButton88);

        jButton89.setText("jButton89");
        jPanel1.add(jButton89);

        jButton90.setText("jButton90");
        jPanel1.add(jButton90);

        jButton92.setText("jButton92");
        jPanel1.add(jButton92);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton50ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
